### ISSUE TITLE
Gmail SMTP server is wrong

### ISSUE THREAD

**Issue by i5o** [helpdesk-z/helpdeskz-dev#11]
it should be smtp.gmail.com as noted in https://support.google.com/mail/answer/7126229?hl=en-GB

https://github.com/helpdesk-z/helpdeskz-dev/blob/e1ff828cc3301280fb983ec8154da12c66e8c8de/hdz/app/Views/staff/email_addresses_form.php#L89

**Comment by helpdesk-z** [comment]
Hi,

That's not an issue, it's just an example, you are free to change it.

**Comment by i5o** [comment]
Yes. But its a wrong example, so its misleading
