### ISSUE TITLE
Add a Select all for api permissions

### ISSUE THREAD

**Issue by i5o** [helpdesk-z/helpdeskz-dev#14]
Kinda similar to phpmyadmin add new user:

![image](https://user-images.githubusercontent.com/2650479/110829369-cb178480-8276-11eb-8e64-d7e26fc9206c.png)

![image](https://user-images.githubusercontent.com/2650479/110829319-bd61ff00-8276-11eb-906c-7b0814b71df3.png)

**Comment by helpdesk-z** [comment]
Thanks for the suggestion, we'll take a note about it.
