### ISSUE TITLE
Editar el logo

### ISSUE THREAD

**Issue by i5o** [helpdesk-z/helpdeskz-dev#15]
(ya vi que hablan espaniol, es mas facil para mi, soy Uruguayo :P)

Pense que cuando pusiera el logo de la empresa se iba a cambiar en el dash de staff, pero no se cambia

![image](https://user-images.githubusercontent.com/2650479/110829601-15006a80-8277-11eb-978f-19d264a3991b.png)

deberia poder cambiarse

**Comment by helpdesk-z** [comment]
Es nuestra marca, no se cambia mediante el script, se puede hacer reemplazando: /assets/helpdeskz/images/logo.png
