### ISSUE TITLE
Missing the install folder

### ISSUE THREAD

**Issue by mmarconm** [helpdesk-z/helpdeskz-dev#2]
I think that the install folder its missing, as a try to install running http://server/support/install and i got a 404 page.

**Comment by helpdesk-z** [comment]
Verify that .htaccess has been uploaded in your server and mod_rewrite is enable.

**Comment by mmarconm** [comment]
Do i need to install composer and install dependencies ?

**Comment by mmarconm** [comment]
Verify that .htaccess has been uploaded in your server and mod_rewrite is enable.
-> Yes, .htaccess was uploaded and mod_rewrite its enable, and when a try to install http://ip_address/support/install i got Not Found, and there is not install folder inside the heskdeskz root folder.

**Comment by helpdesk-z** [comment]
The script includes the dependencies, so it's not necessary to install anything else.
If you get error 404 then the routing is not working, when you visit http://ip_address/support/ do you get any error?

**Comment by mmarconm** [comment]
> The script includes the dependencies, so it's not necessary to install anything else.
> If you get error 404 then the routing is not working, when you visit http://ip_address/support/ do you get any error?

I got just a page 404, i enable mode_rewrite as you said but the problem continue. follow the link with some prints screen
print screen link: 
![explorer_yBcRASZMAU](https://user-images.githubusercontent.com/2564100/106165932-0136f400-6162-11eb-8123-787f651b8592.png)
https://ibb.co/j8YMj8q

**Comment by helpdesk-z** [comment]
If you get that error, it means the rewrite rule is not working
Are you using apache right? Because if you are under nginx, then the rewrite rule wont work with the htaccess.

If you are under apache, edit the htaccess and use this code:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
```
If it does not work, then the mod rewrite is not active/working
PS: If you have activated the mod rewrite, do not forget to restart your apache server

**Comment by mmarconm** [comment]
Hello, Yes i enable rewrite and restarted the apache2 service. i will follow the steps above and try again. Thank you

Observation: I was wondering that in an older project of helpdeskz [](https://github.com/evolutionscript/HelpDeskZ-1.0), there is a folder install on the root folder. and in this project there is not install folder anymore. 

If works. do you authorize me to make a video, installing Helpdeskz to help others ?

I would like to help on this project, but unfortunately do not now Php, just python ":(

**Comment by helpdesk-z** [comment]
Sure, you can make videos about installation.

So I can close this issue, right?

**Comment by mmarconm** [comment]
I will do a new install of debian 10, and reinstall again. this .htaccess that you mentioned above to edit the config 
.... is it the support/.htaccess?

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

**Comment by mmarconm** [comment]
I did the steps, edited the .htacess but didnt work, i give up, you can close the request. thank you for your help and attention

**Comment by mmarconm** [comment]
I edit apache2 files and php.ini, change the folder permission and change the productionp.php init_set 0 to 1. and it works

**Comment by Sphincz** [comment]
I'm still having this issue. Install location gives a 404 error.
Fresh install of HDZ 2.0.2.
Help would much appreciated. Thank you,

**Comment by helpdesk-z** [comment]
Go to your site and visit this http://yoursite.com/index.php/install
If it works, then your mod rewrite is not configured

**Comment by balyam** [comment]
After "/install" running I've got blank page with text "index.php". I spent few hours to find what was wrong with my installation. 
Please, check that mod_rewrite is enabled or just run "sudo a2enmod rewrite" :(

**Comment by DragonflyMAD** [comment]
Still get error 404, i changed .htaccess for that is posted, but still same

**Comment by DragonflyMAD** [comment]
> I edit apache2 files and php.ini, change the folder permission and change the productionp.php init_set 0 to 1. and it works

Can u write exacly what have u changed ?

**Comment by DragonflyMAD** [comment]
U need to change AllowOverride None to All:

<Directory /var/www/>
    AllowOverride All
 </Directory>

in /etc/apache2/apache2.conf

**Comment by swealpha** [comment]
how to do if you are under litespeed? :(
