### ISSUE TITLE
Here is a contribution for your project 

### ISSUE THREAD

**Issue by Xeros91** [helpdesk-z/helpdeskz-dev#23]
I have uploaded the French translation to the forum, but you can also add it here. 

[helpdeskZ translation fr.zip](https://github.com/helpdesk-z/helpdeskz-dev/files/6385891/helpdeskZ.translation.fr.zip)

**Comment by helpdesk-z** [comment]
Thanks for your contribution however Api was not translated, we'll add it with a warning.
