### ISSUE TITLE
adapting the code to ci4

### ISSUE THREAD

**Issue by desk-99** [helpdesk-z/helpdeskz-dev#24]
In codeigniter4 getNumRows() should be used instead of num_rows so please replace 
`if($q->resultID->num_rows`
 with 
`if($q->getNumRows()`
in the files in the hdz/app/Libraries directory.

**Comment by desk-99** [comment]
I made pull request

**Comment by helpdesk-z** [comment]
Thanks, that feature was not available in previous codeigniter version.
