### ISSUE TITLE
Installation TYPE ERROR

### ISSUE THREAD

**Issue by cheesgno** [helpdesk-z/helpdeskz-dev#7]
Hi!
I'm trying to install the latest release of Helpdeskz but when I try to start the initial configuration  I get the following error:

`TypeError
Argument 1 passed to CodeIgniter\Database\BaseBuilder::get() must be of the type int or null, string given, called in /var/www/html/support/hdz/framework/Model.php on line 1818 `

My test environment is based on PHP 7.3 and Apache Web Server

Moreover I wondering if there is a docker version of this software available.

Can you help me?

Thanks in advanced

**Comment by helpdesk-z** [comment]
Hi,
Download the latest script package here: https://github.com/helpdesk-z/helpdeskz-dev/archive/master.zip
It contains the update of codeigniter for php 7.3

**Comment by cheesgno** [comment]
Hi,
Thanks for your quick help.
I tried the latest package both with php 7.3 and 7.2 but I've got this error (I think is the same but in other line of code) 

```
TypeError
Argument 1 passed to CodeIgniter\Database\BaseBuilder::get() must be of the type integer or null, string given, called in /var/www/html/support/hdz/framework/Model.php on line 836 
```

**Comment by helpdesk-z** [comment]
Did you rename the file Helpdesk.new.php to Helpdesk.php from /hdz/app/Config/HelpDeskz ?. Also edit the content to set your database connection.

**Comment by cheesgno** [comment]
Yes because with an erroneous configuration I've got an error about the db connection.
I don't know what was the error but I'm reinstalled all the libraries and now I'm able to install your software.
Thanks for your help

**Comment by mfrederico** [comment]
I'm still getting this error, and I've updated everything. .  
@cheesgno  - what "libraries" did you reinstall?
