### ISSUE TITLE
Not able to change default email

### ISSUE THREAD

**Issue by i5o** [helpdesk-z/helpdeskz-dev#8]
Hello, this line is not allowing me to change the default email in settings.

https://github.com/helpdesk-z/helpdeskz-dev/blob/9bf009a07a3539a0e25955b5d53295d33ff1ddae/hdz/app/Controllers/Staff/Settings.php#L346

I basically changed it to `if (false)` in order to be able to do stuff

**Comment by helpdesk-z** [comment]
Fixed, thank you!
