### ISSUE TITLE
Wrong URL in README.md

### ISSUE THREAD

**Issue by i5o** [helpdesk-z/helpdeskz-dev#9]
This line is pointing to a 404 url.

https://github.com/helpdesk-z/helpdeskz-dev/blob/9bf009a07a3539a0e25955b5d53295d33ff1ddae/README.md#L46

Think it should be
https://docs.helpdeskz.com/en/latest/configuration/email_imap/

**Comment by helpdesk-z** [comment]
Thanks, it's fixed.
